# Generated by Django 4.2.25 on 2025-11-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyrecord',
            old_name='Policy',
            new_name='policy',
        ),
    ]
