# Generated by Django 4.2.25 on 2025-11-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_rename_policy_policyrecord_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrecord',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('policy_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.policyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('creation_date', models.DateField(auto_now=True)),
                ('policy_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.policyrecord')),
            ],
        ),
    ]
